language: cpp
compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libgtk2.0-dev gettext git-core cmake gpsd gpsd-clients libgps-dev build-essential wx-common libwxgtk2.8-dev libglu1-mesa-dev libgtk2.0-dev wx2.8-headers libbz2-dev libtinyxml-dev libportaudio2 portaudio19-dev
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
