branches:
  only:
    - master
  #  - appveyorbuild
  # blacklist
  #except:
  #  - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
clone_folder: c:\projects\objsearch_pi
shallow_clone: true
image:
- Visual Studio 2015

platform:
  - Win32

configuration:
  - Release

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'

  # sent environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.0.2
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - cmd: SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # install dependencies:
  - choco install poedit nsis -x86

  # Download and unzip wxwidgets
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/wxwindows/3.0.2/wxWidgets-3.0.2.zip
  - cmd: 7z x wxwidgets-3.0.2.zip -o%WXWIN% > null

  # some debugging information
  - set
  # - cmake --help

  # build wxWidgets
  - cmd: cd %WXWIN%\build\msw\
  - cmd: nmake -f makefile.vc BUILD=release SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_
  - cmd: nmake -f makefile.vc BUILD=debug SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_

  
build:

before_build:
  - cd c:\project\objsearch_pi
  - mkdir build
  - cd build
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/opencpnplugins/opencpn_packaging_data/OpenCPN_buildwin.7z
  - cmd: 7z x -y OpenCPN_buildwin.7z -oc:\project\objsearch_pi
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/opencpnplugins/opencpn_lib/4.2-vc120_xp/opencpn.lib
  - cmake -T v120_xp ..

build_script:
  - cmake --build . --config Release --target package
  
#after_build:
#  - cmd: package.bat

artifacts:
  - path: build\objsearch_pi*.exe
    name: installer

deploy: OFF
#  - provider: FTP
#    server: 
#      secure: kZT7rsbEPGQ0fC2GFRBGfL2vPwUgih2JkwjbSuw00T8=
#    username:
#      secure: YJzwsi4wfSezFLqaB9uiww==
#    password:
#      secure: EQ3xa2LoRgelAdE57+qakQ==
#    folder: .\rpcs3\
#    enable_ssl: false
  
test: OFF

